name: NTxPred2
channels:
  - defaults
  - conda-forge
  - pytorch 
dependencies:
  - python=3.10.7
  - pytorch=2.6.0
  - scikit-learn=1.5.2
  - numpy=1.25.2
  - pandas=1.5.3
  - joblib=1.4.2
  - biopython=1.81
  - tqdm=4.64.1
  - pip
  - pip:
      - transformers==4.34.0
      - torchdata 
      - torchtext 
      - torchvision 
